### ISSUE TITLE
Problem with new lines in JSON files

### ISSUE THREAD

**Issue by harrison314** [jsakamoto/Toolbelt.Blazor.I18nText#11]
If i use text with new lines (\n) in JSON file, eg:
```json
{
	"Hello": "Hello text\nwith new line\n"
}
```
then generate non valid comments in  _C#_ code:
![image](https://user-images.githubusercontent.com/12501763/66391471-8165a300-e9cd-11e9-8181-c5930ab50739.png)

**Comment by jsakamoto** [comment]
I fixed this issue at commit 866658f6cb75784b60b8dbe7b1f5a1e75fb21106.

Please update the package to latest version.

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/7.0.1.1

Thank you for your reporting.  
Especially, the screen shot of the problem was very useful for resolve this issue! 👍

**Comment by harrison314** [comment]
@jsakamoto thanks
