### ISSUE TITLE
Can load translate text if we are not login

### ISSUE THREAD

**Issue by eanpr** [jsakamoto/Toolbelt.Blazor.I18nText#29]
Hi,
I use this package in blazor web assembly. If I am not login my application render error. but after after I login it working perfect.

Can you help me how to fix this?
Thank

**Comment by jsakamoto** [comment]
Sorry, I can't help you due to I could not understand what happens in your app.

Anyway, depending on your post, it seems a general problem on the Blazor WebAssembly app, not an issue of this package.

I recommend that you should ask to "stakoverflow" (https://stackoverflow.com/questions/tagged/blazor ) with disclosing your source code.

P.S.
By the way, this package will work fine regardless of whether you are logged in or not.

See also the Blazor WebAssembly app below.

- https://taptotweetreserved.azurewebsites.net/

(On this app, you can change the language from the footer of this app before you logged in.)

**Comment by Gambero81** [comment]
i have the same issue, i use asp.net core authentication and if you are not logged AccessTokenNotAvailableException is raised

**Comment by Gambero81** [comment]
@jsakamoto can we have support on this issue? with this problem the library is not usable with default asp.net core authentication identity server and jwt.

Thanks

**Comment by jsakamoto** [comment]
@Gambero81 

Could you help me by attach the zip packaged project file which can reproduce your problem?

**Comment by Gambero81** [comment]
I have created a new Blazor WebAssembly App from Visual Studio template with this settings:  
- "Individual User Accounts" authentication
- ASP.NET Core hosted
- Progressive Web Application

I have installed the i18nText package with nuGet, added service in Main and ConfigureServices methods and edited the Index.razor page as follow:

![MyBlazorAppIndexRazor](https://user-images.githubusercontent.com/13186600/83757459-cdf2a280-a670-11ea-9e87-c0e91f1e8f4c.png)

when i run the application the page load without translation and in devtools console return AccessTokenNotAvailableException after the json get request

![MyBlazorAppError](https://user-images.githubusercontent.com/13186600/83758333-34c48b80-a672-11ea-90b2-ba2fa60599d3.png)

This is the project:

[MyBlazorApp.zip](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/files/4730098/MyBlazorApp.zip)

Thank you very much @jsakamoto

**Comment by jsakamoto** [comment]
@Gambero81 @eanpr 
Hi, everyone.

As I expect, the problem is not the "i18n text" package itself' s problem.

The most fundamental cause is, the default implementation is configured to try to attach access token all HTTP requests even if the request URL is allowed to anonymous access.

Therefore, I changed the code to attach access token to only HTTP requests to the limited specified URL.

I attach my solution as below.

[MyBlazorApp.zip](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/files/4739438/MyBlazorApp.zip)

The zip file includes local git repository, so you can see the change log.

![image](https://user-images.githubusercontent.com/95908/83937767-a7686f00-a80a-11ea-88be-7da470665b05.png)

I hope this my solution is helpful for you.

P.S.
Really appreciate for you, @Gambero81 !
You sent to me the detail of the project to reproduce the problem. This was very very helpful for me to work on this problem, and save my time.
Thanks!

**Comment by jsakamoto** [comment]
@Gambero81 @eanpr
Hi, everyone.

Today, I published v.9.1 package.

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/9.1.0

This version improved to works fine out of the box even on an access token-based authorization enabled site.

Thanks for your contribution! 👍
